### ISSUE TITLE
Support older Android versions

### ISSUE THREAD

**Issue by starryalley** [starryalley/AmbitSync#1]
Currently the project sets min SDK version to 23 (Android M, 6.0). I have only tested it with my Ambit 2 on Android 7.0/8.0/8.1. This issue is open to support older Android versions.

**Comment by starryalley** [comment]
Set min SDK to 17 (Android JellyBean MR1, 4.2) and rebuild the apk:
[app-release.apk.zip](https://github.com/starryalley/AmbitSync/files/1713170/app-release.apk.zip)

@skinnie could you test with the apk? I'll find my old phones running 5.0 (don't have 4.x devices now) and test it. But before that I should buy a micro-B OTG cable.

**Comment by skinnie** [comment]
Works fine on Nexus 7 3g 2012 with 4.4.4 Rom and Ambit 2 Sapphire

**Comment by skinnie** [comment]
Also works on LG G Pad 8.3 with CM13 based on Android 6.0

**Comment by starryalley** [comment]
Good to know that. Thank you for these tests!

**Comment by starryalley** [comment]
Updated apk in the latest commit. Also published to google play store. Close this issue.
