### ISSUE TITLE
Availability on F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [starryalley/AmbitSync#4]
I've just [opened a request-for-packaging at F-Droid](https://gitlab.com/fdroid/rfp/issues/622): It would be nice to see your app there. Would you agree to have your app listed at that place?

In case you don't know F-Droid: that's a repository for free and open source apps, especially caring for the users' privacy – as you do with your app, which is why I consider that a perfect match. I gladly answer any questions you might have, and the F-Droid crew will certainly help you getting your app listed.

As far as I (not being an Android dev) can see, you're already prepared for that: I couldn't detect any "proprietary library", and using tags will make automatical updates easy.

**Comment by starryalley** [comment]
Yes go ahead. Thanks.

**Comment by IzzySoft** [comment]
Thanks a lot! Progress looks good already. Now it just needs to be picked up by a maintainer, and a "build recipe" set up. Will take a few more days (or maybe weeks). Until then, you can [find it in my repo](https://apt.izzysoft.de/fdroid/index/apk/idv.markkuo.ambitsync) (which often acts as a kind of "staging area", as processing takes a while in the official one :wink:)
